### ISSUE TITLE
I get the error

### ISSUE THREAD

**Issue by pitersdagger** [limonadev/flutter_culqi#1] opened 2020-03-15 12:59 UTC
hello
nice to meet you
Can we discuss more about the package developing?
How about the payment?

**Comment by limonadev** [comment] 2020-03-15 13:11
Hi! What's the error you get? (From [this](https://github.com/limonadev/flutter_culqi/blob/master/lib/src/culqi_response.dart) or is another type of error?)

**Comment by pitersdagger** [comment] 2020-03-15 14:38
hi, thanks for your reply.
I built the source file in the github you uploaded.
When I input  the fields, then I click the get token button, the result is error(timeout error)

**Comment by limonadev** [comment] 2020-03-15 14:52
Can you share the output of your console or screenshot when run the app?  (The part showing the error). Also, did you run the app as debug or as release?

**Comment by pitersdagger** [comment] 2020-03-15 14:54
I run the app as debug.
the error result
Error obtaining Token from Culqi:
I/flutter ( 6092): ErrorCode: 504
I/flutter ( 6092): ErrorMessage: null
I/flutter ( 6092): ErrorType: CulqiErrorType.ServerValidationFailed
I/flutter ( 6092): {"message": "Endpoint request timed out"}

**Comment by pitersdagger** [comment] 2020-03-15 14:56
the input value:
card number: 4111111111111111
cvv: 123
email:  jorge.neciosup.casas@gmail.com

**Comment by limonadev** [comment] 2020-03-15 15:39
I was able to reproduce your error but I couldn't figure out why is happening, so I clone the [Culqi Android Repo](https://github.com/culqi/culqi-android) and test if that works. Sadly, the official Culqi Android Repo also returns a 504 HTTP Response (Endpoint request timed out). So, I guess is an error or maintenance on the Culqi server (because even its official SDK returns 504). Until the server came back I will maintain this issue as open.
If you have another issue or question, I will be glad to help you :)

**Comment by pitersdagger** [comment] 2020-03-15 16:06
thanks.

**Comment by pitersdagger** [comment] 2020-03-16 03:11
And in the package, there are getToken and Widget for the culqi.
Could you tell me when you add the payment function in the package?

**Comment by limonadev** [comment] 2020-03-16 15:44
Probably never. The way Culqi works is using public and private key. You encrypt the user data (card number, cvv, etc) using the public key generating a token. You send that token to your server, and your server has to use the private key to make payments.

This package is for clients, to generate tokens using the public key. On your server you need to implement the Culqi server side. Maybe in the future I'll create a new Dart package to handle that on server side, but this specific package is only for Flutter (Flutter doesn't work on server side).

**Comment by limonadev** [comment] 2020-03-16 19:34
The issue on Culqi server side was fixed. I close this for now but you can re open it if you need.

**Closed as completed by limonadev** 2020-03-16 19:34 UTC
Labels: bug, help wanted
